config/routes.rb
Rails.application.routes.draw do
  resources :quotations
  resources :customers do
    resources :quotations
  end
  devise_for :users
  get 'home/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "customers#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/customer.rb
class Customer < ApplicationRecord
    has_many :quotations, dependent: :destroy
    validates :first_name, :phone, :email, presence: true
    validates :phone, length: { minimum: 10, maximum: 14 }
    validates :email, format: { with: URI::MailTo::EMAIL_REGEXP, message: "must be a valid email address" }
    accepts_nested_attributes_for :quotations, allow_destroy: true
end

app/models/quotation.rb
class Quotation < ApplicationRecord
  belongs_to :customer
  validates :attachment, :date, presence: true
  has_one_attached :attachment
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :first_name, :last_name, :phone, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :phone])
  end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_customer, only: %i[ show edit update destroy ]

  # GET /customers or /customers.json
  def index
    @customers = Customer.all
    @customers = @customers.where(created_at: params[:date].to_date.beginning_of_day..params[:date].to_date.end_of_day) if params[:date].present?
    @customers = @customers.where(first_name: params[:name]) if params[:name].present?
    @customers = @customers.where(id: params[:id]) if params[:id].present?
  end

  # GET /customers/1 or /customers/1.json
  def show
  end

  # GET /customers/new
  def new
    @customer = Customer.new
    @customer.quotations.build
  end

  # GET /customers/1/edit
  def edit
    @customer.quotations.build if @customer.quotations.empty?
  end

  # POST /customers or /customers.json
  def create
    @customer = Customer.new(customer_params)

    respond_to do |format|
      if @customer.save
        format.html { redirect_to customer_url(@customer), notice: "Customer was successfully created." }
        format.json { render :show, status: :created, location: @customer }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /customers/1 or /customers/1.json
  def update
    respond_to do |format|
      if @customer.update(customer_params)
        format.html { redirect_to customer_url(@customer), notice: "Customer was successfully updated." }
        format.json { render :show, status: :ok, location: @customer }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customers/1 or /customers/1.json
  def destroy
    @customer.destroy!

    respond_to do |format|
      format.html { redirect_to customers_url, notice: "Customer was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_customer
      @customer = Customer.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def customer_params
      params.require(:customer).permit(:first_name, :last_name, :phone, :email, quotations_attributes: [:id, :date, :attachment,:comment, :_destroy])
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!
  def index
  end
end

app/controllers/quotations_controller.rb
class QuotationsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_quotation, only: %i[ show edit update destroy ]

  # GET /quotations or /quotations.json
  def index
    @quotations = Quotation.all
    @quotations = @quotations.where(date: params[:date].to_date.beginning_of_day..params[:date].to_date.end_of_day) if params[:date].present?
    @quotations = @quotations.where(customer_id: params[:customer_id]) if params[:customer_id].present?
    @quotations = @quotations.joins(:customer).where("customers.first_name LIKE :name OR customers.last_name LIKE :name", name: "%#{params[:customer_name]}%") if params[:customer_name].present?
    @quotations = @quotations.where("attachment_filename LIKE ?", "%#{params[:attachment_filename]}%") if params[:attachment_filename].present?
  end

  # GET /quotations/1 or /quotations/1.json
  def show
  end

  # GET /quotations/new
  def new
    @quotation = Quotation.new
  end

  # GET /quotations/1/edit
  def edit
  end

  # POST /quotations or /quotations.json
  def create
    @quotation = Quotation.new(quotation_params)

    respond_to do |format|
      if @quotation.save
        format.html { redirect_to quotation_url(@quotation), notice: "Quotation was successfully created." }
        format.json { render :show, status: :created, location: @quotation }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @quotation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /quotations/1 or /quotations/1.json
  def update
    respond_to do |format|
      if @quotation.update(quotation_params)
        format.html { redirect_to quotation_url(@quotation), notice: "Quotation was successfully updated." }
        format.json { render :show, status: :ok, location: @quotation }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @quotation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /quotations/1 or /quotations/1.json
  def destroy
    @quotation.destroy!

    respond_to do |format|
      format.html { redirect_to quotations_url, notice: "Quotation was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_quotation
      @quotation = Quotation.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def quotation_params
      params.require(:quotation).permit(:attachment, :date, :comment, :customer_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/quotations_helper.rb
module QuotationsHelper
end

app/views/customers/_customer.html.erb
<div id="<%= dom_id customer %>" class="card mb-3">
  <div class="card-body">
    <h3 class="card-title">Customer Information</h3>

    <p class="card-text">
      <strong>First Name:</strong>
      <%= customer.first_name %>
    </p>

    <p class="card-text">
      <strong>Last Name:</strong>
      <%= customer.last_name %>
    </p>

    <p class="card-text">
      <strong>Phone:</strong>
      <%= customer.phone %>
    </p>

    <p class="card-text">
      <strong>Email:</strong>
      <%= customer.email %>
    </p>

    <% if customer.quotations.any? %>
      <h4 class="mt-4">Quotations</h4>
      <ul>
        <% customer.quotations.each do |quotation| %>
          <li>
            <%= link_to quotation.attachment.filename, quotation_path(quotation), class: "btn btn-link" %> |
            <strong>Date:</strong> <%= quotation.date %> |
            <%= link_to url_for(quotation.attachment), class: "btn btn-link" do %>
              <% if quotation.attachment.attached? %>
                <i class="fa bi-download"></i> <!-- Bootstrap Icons download icon -->
              <% end %>
            <% end %> |           
            <strong>Comment:</strong> <%= quotation.comment %>
          </li>
        <% end %>
      </ul>
    <% end %>
  </div>
</div>

app/views/customers/_form.html.erb
<%= bootstrap_form_for(@customer) do |form| %>
  <% if @customer.errors.any? %>
    <div class="alert alert-danger">
      <ul>
        <% @customer.errors.full_messages.each do |error_message| %>
          <li><%= error_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="col-md-6">
      <%= form.text_field :first_name, class: "form-control", placeholder: "First Name" %>
    </div>
    <div class="col-md-6">
      <%= form.text_field :last_name, class: "form-control", placeholder: "Last Name" %>
    </div>
  </div>

  <div class="row">
    <div class="col-md-6">
      <%= form.text_field :phone, class: "form-control", placeholder: "Phone" %>
    </div>
    <div class="col-md-6">
      <%= form.text_field :email, class: "form-control", placeholder: "Email" %>
    </div>
  </div>

  <div class="row">
    <div class="col-md-12">
      <h3>Quotation Information</h3>
    </div>
  </div>

  <div class="row">
    <div class="col-md-12">
      <%= form.fields_for :quotations do |quotation_fields| %>
        <%= render 'quotation_fields', f: quotation_fields %>
      <% end %>
    </div>
    <div class="col-md-12">
      <%= link_to_add_association 'Add Quotation', form, :quotations, class: 'btn btn-secondary btn-sm mt-2' %>
    </div>
  </div>


  <div class="text-center mt-3">
    <%= form.submit "Submit", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/customers/_quotation_fields.html.erb
<div class="nested-fields border border-dashed border-primary rounded p-3 mb-3">
    <div class="row">
        <div class="col-md-3">
            <%= f.date_field :date, class: "form-control" %>
        </div>
        <div class="col-md-3">
            <%= f.file_field :attachment, class: "form-control", accept: 'application/pdf, application/zip,application/vnd.openxmlformats-officedocument.wordprocessingml.document' %>
        </div>
        <div class="col-md-3">
            <%= f.text_field :comment, class: "form-control"%>
        </div>
        <div class="col-md-3" style="margin-top: 20px;">
            <%= link_to_remove_association "Remove Quotation", f, class: "btn btn-danger mt-2" %>
        </div>
    </div>
</div>

app/views/customers/edit.html.erb
<div class="container">
  <h1>Editing customer</h1>

  <%= render "form", customer: @customer %>

  <hr>
  <div class="row">
    <div class="col-md-2">
      <%= link_to "Show this customer", @customer, class: "btn btn-primary btn-block" %>
    </div>
    <div class="col-md-2">
      <%= link_to "Back to customers", customers_path, class: "btn btn-success btn-block" %>
    </div>
  </div>

</div>

app/views/customers/index.html.erb
<div class="container bg-light">
  <p style="color: green"><%= notice %></p>
 <%= form_with(url: customers_path, method: "get", local: true) do |form| %>
    <div class="row">
      <div class="col-md-4">
        <div class="form-group">
          <%= form.label :date, "Date:" %>
          <%= form.date_field :date, class: "form-control" %>
        </div>
      </div>
      
      <div class="col-md-4">
        <div class="form-group">
          <%= form.label :name, "Name:" %>
          <%= form.text_field :name, class: "form-control" %>
        </div>
      </div>

      <div class="col-md-4">
        <div class="form-group">
          <%= form.label :id, "ID:" %>
          <%= form.number_field :id, class: "form-control" %>
        </div>
      </div>
    </div>
    <%= form.submit "Filter", class: "btn btn-primary" %>
  <% end %>

  <hr>
  <div class="row">
    <div class="col-sm-8"><h2>Customers</h2></div>
    <div class="col-sm-4 text-end">
      <%= link_to "New customer", new_customer_path, class: "btn btn-success" %>
    </div>
  </div>
  <table class="table table-striped table-hover">
    <thead>
      <tr>
        <th>First Name</th>
        <th>Last Name</th>
        <th>Phone</th>
        <th>Quotations</th>
        <th>Action</th>
      </tr>
    </thead>
    <tbody>
      <% @customers.each do |customer| %>
        <tr>
          <td><%= customer.first_name %></td>
          <td><%= customer.last_name %></td>
          <td><%= customer.phone %></td>
          <td>
            <% quotation = customer.quotations&.first%>
            <%= link_to quotation&.attachment&.filename, url_for(quotation&.attachment) if quotation&.attachment&.attached? %>
          </td>
          <td>
            <%= link_to "Show", customer, class: "btn btn-primary btn-sm me-1" %>
            <%= link_to "Edit", edit_customer_path(customer), class: "btn btn-warning btn-sm me-1" %>
            <%= link_to "Delete", customer, method: :delete, class: "btn btn-danger btn-sm", data: { confirm: "Are you sure you want to delete this customer?" } %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/customers/new.html.erb
<div class="container">
  <h1>New customer</h1>

  <%= render "form", customer: @customer %>

  <br>

  <div>
    <%= link_to "Back to customers", customers_path %>
  </div>
</div>

app/views/customers/show.html.erb
<div class="container">
  <p style="color: green"><%= notice %></p>

  <%= render @customer %>

  <div class="row">
    <div class="col-md-2">
      <%= link_to "Edit this customer", edit_customer_path(@customer), class: "btn btn-primary btn-block" %>
    </div>
    <div class="col-md-2">
      <%= link_to "Back to customers", customers_path, class: "btn btn-secondary btn-block" %>
    </div>
    <div class="col-md-2">
      <%= button_to "Delete this customer", @customer, method: :delete , class: "btn btn-danger btn-block" %>
    </div>
  </div>
</div>

app/views/home/index.html.erb
<% if user_signed_in? %> 
 <h1>Home#index</h1>
 <h2>Welcome <%= current_user.first_name %> <%= current_user.last_name%></h2>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SpmsTool</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= javascript_include_tag "jquery" %>

  </head>

  <body> 
    <% if user_signed_in? %> 
      <%= render "shared/header"%>
    <% end %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/quotations/_form.html.erb
<%= bootstrap_form_for(@quotation) do |form| %>
  <% if @quotation.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(quotation.errors.count, "error") %> prohibited this quotation from being saved:</h2>

      <ul>
        <% @quotation.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.file_field :attachment, class: "form-control", accept: 'application/pdf, 
    application/zip,application/vnd.openxmlformats-officedocument.wordprocessingml.document' %>
  </div>

  <div>
    <%= form.date_field :date %>
  </div>

  <div>
    <%= form.text_area :comment %>
  </div>

  <div>
    <%= form.collection_select :customer_id, Customer.all, :id, :first_name, { prompt: "Select a customer" }, { class: "form-control" } %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/quotations/_quotation.html.erb
<div id="<%= dom_id quotation %>" class="card mb-3">
  <div class="card-body">
    <h3 class="card-title">Quotation Information</h3>

    <p class="card-text">
      <strong>File Name:</strong>
      <%= quotation.attachment&.filename %>
    </p>

    <p class="card-text">
      <strong>File Link:</strong>
      <%= link_to quotation.attachment.filename, url_for(quotation.attachment) %>
    </p>

    <p class="card-text">
      <strong>Date:</strong>
      <%= quotation.date %>
    </p>

    <p class="card-text">
      <strong>Comment:</strong>
      <%= quotation.comment %>
    </p>

    <p class="card-text">
      <strong>Customer:</strong>
      <%= quotation.customer.first_name %>
    </p>
  </div>
</div>

app/views/quotations/edit.html.erb
<div class="container">
  <h1>Editing quotation</h1>

  <%= render "form", quotation: @quotation %>
  <hr>
  <div class="row">
    <div class="col-md-2">
      <%= link_to "Show this quotation", @quotation, class: "btn btn-primary btn-block" %>
    </div>
    <div class="col-md-2">
      <%= link_to "Back to quotations", quotations_path, class: "btn btn-success btn-block" %>
    </div>
  </div>
</div>

app/views/quotations/index.html.erb
<div class="container bg-light">
  <p style="color: green"><%= notice %></p>
  <%= form_with(url: quotations_path, method: "get", local: true) do |form| %>
    <div class="row">
      <div class="col-md-4">
        <div class="form-group">
          <%= form.label :date, "Date:" %>
          <%= form.date_field :date, class: "form-control" %>
        </div>
      </div>
      
      <div class="col-md-4">
        <div class="form-group">
          <%= form.label :customer_id, "Customer ID:" %>
          <%= form.number_field :customer_id, class: "form-control" %>
        </div>
      </div>

      <div class="col-md-4">
        <div class="form-group">
          <%= form.label :customer_name, "Customer Name:" %>
          <%= form.collection_select :customer_name, Customer.distinct.pluck(:first_name), :to_s, :to_s, { include_blank: true }, class: "form-control" %>
        </div>
      </div>

      <div class="col-md-4">
        <div class="form-group">
          <%= form.label :attachment_filename, "Attachment Filename:" %>
          <%= form.text_field :attachment_filename, class: "form-control" %>
        </div>
      </div>
    </div>

    <%= form.submit "Filter", class: "btn btn-primary" %>
  <% end %>

  <hr>

  <div class="row">
    <div class="col-sm-8"><h2>Quotations</h2></div>
    <div class="col-sm-4 text-end">
      <%= link_to "New Quotation", new_quotation_path, class: "btn btn-primary" %>
    </div>
  </div>
  <table class="table table-striped table-hover">
    <thead>
      <tr>
        <th>Date</th>
        <th>Customer Name</th>
        <th>File</th>
        <th>Comment</th>
        <th>Action</th>
      </tr>
    </thead>
    <tbody>
      <% @quotations.each do |quotation| %>
        <tr>
          <td><%= quotation.date %></td>
          <td><%= quotation.customer.first_name %></td>
          <td><%= quotation.attachment&.filename %></td>
          <td><%= quotation.comment %></td>
          <td>
            <%= link_to "Show", quotation, class: "btn btn-primary btn-sm me-1" %>
            <%= link_to "Edit", edit_quotation_path(quotation), class: "btn btn-warning btn-sm me-1" %>
            <%= link_to "Delete", quotation, method: :delete, class: "btn btn-danger btn-sm", data: { confirm: "Are you sure you want to delete this quotation?" } %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/quotations/new.html.erb
<div class="container">
  <h1>New quotation</h1>

  <%= render "form", quotation: @quotation %>

  <br>

  <div>
    <%= link_to "Back to quotations", quotations_path, class: "btn btn-danger" %>
  </div>
</div>

app/views/quotations/show.html.erb
<div class="container">
  <p style="color: green"><%= notice %></p>

  <%= render @quotation %>

  <div class="row">
    <div class="col-md-2">
      <%= link_to "Edit this Quotation", edit_quotation_path(@quotation), class: "btn btn-primary btn-block" %>
    </div>
    <div class="col-md-2">
      <%= link_to "Back to Quotations", quotations_path, class: "btn btn-secondary btn-block" %>
    </div>
    <div class="col-md-2">
      <%= button_to "Delete this Quotation", @quotation, method: :delete , class: "btn btn-danger btn-block" %>
    </div>
  </div>
</div>

app/views/shared/_header.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">SPMS-Tool</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
            <%= link_to "Home", customers_path, class: "nav-link active", aria: { current: "page" } %>
        </li>
        <li class="nav-item">
          <%= link_to "Customers", customers_path, class: "nav-link active", aria: { current: "page" } %>
        </li>
        <li class="nav-item">
          <%= link_to "Quotations", quotations_path, class: "nav-link active", aria: { current: "page" } %>
        </li>
      </ul>
    </div>
    <%= link_to "#{current_user.first_name} #{current_user.last_name}", edit_user_registration_path(current_user) %>
    <%= button_to "Sign out", destroy_user_session_path, method: :delete, class: "btn btn-danger" %> 
  </div>
  </nav>